version: '3.8'

services:
  service-app:
    build:
      context: ./service-app
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"     
    environment:
      - SIRIUS_BASE_URL=${SIRIUS_BASE_URL}
      - PORT=${HTTP_PORT}  
      - PROJECT_PATH=${PROJECT_PATH}
    command: ./app
    networks:
      - opg-sirius_default

networks:
  opg-sirius_default:
    external: true
