services:
  localstack: !reset null
  sirius-mock: !reset null

  service-app:
    environment:
      - SIRIUS_BASE_URL=http://api
    networks:
      - opg-sirius_default
    depends_on: !reset null

  service-app-test:
    environment:
      - SIRIUS_BASE_URL=http://api
    networks:
      - opg-sirius_default
    depends_on: !reset null

networks:
  opg-sirius_default:
    external: true
