version: '3.8'

services:
  service-app:
    build:
      context: ./service-app
    ports:
      - "8081:8081"     
    environment:
      - PORT=8081
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - SECRETS_MANAGER_PREFIX=local/
      - SIRIUS_BASE_URL=http://api
    command: ./app
    depends_on:
      - localstack
    networks:
      - opg-scanning_network
      - opg-sirius_default

  localstack:
    image: localstack/localstack:3.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack/init:/etc/localstack/init/ready.d"
      - "./scripts/localstack/wait:/scripts/wait"
      - "./localstack-data:/var/lib/localstack/data"
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      SERVICES: "s3,dynamodb,secretsmanager,sqs,ssm,events"
      DEBUG: 1
      DATA_DIR: /var/lib/localstack/data
    networks:
      opg-scanning_network:
        aliases:
          - sqs.eu-west-1.localhost.localstack.cloud
    ports:
      - "4566:4566"
      - "4571:4571"
    healthcheck:
      test: bash /scripts/wait/healthcheck.sh
      interval: 20s
      timeout: 30s
      retries: 50
    restart: unless-stopped

networks:
  opg-scanning_network:
    driver: bridge
  opg-sirius_default:
    external: true  